// Build the webview stylesheet with Tailwind, then codegen it into a TS module
// so the extension host and tests import the CSS as a plain string (no runtime
// fs, CSP-safe inline <style nonce>). Run before tsc.
const { execFileSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const input = path.join(root, "src", "webview", "tailwind.css");
const cssOut = path.join(root, ".build", "styles.css");
const tsOut = path.join(root, "src", "webview", "styles.generated.ts");

fs.mkdirSync(path.dirname(cssOut), { recursive: true });

const bin = path.join(root, "node_modules", ".bin", process.platform === "win32" ? "tailwindcss.cmd" : "tailwindcss");
execFileSync(bin, ["-i", input, "-o", cssOut, "--minify"], { stdio: "inherit" });

const css = fs.readFileSync(cssOut, "utf8");
const banner = "// AUTO-GENERATED by scripts/build-css.cjs from tailwind.css. Do not edit.\n";
fs.writeFileSync(tsOut, `${banner}export const CSS = ${JSON.stringify(css)};\n`);
console.log(`styles.generated.ts: ${css.length} bytes of CSS`);
